INSERT INTO countries (id, name, iso, phonecode, currency, flag, code) VALUES
(1, 'Afghanistan', 'AF', '93', 'AFN', '🇦🇫', 'afghanistan'),
(2, 'Albania', 'AL', '355', 'ALL', '🇦🇱', 'albania'),
(3, 'Algeria', 'DZ', '213', 'DZD', '🇩🇿', 'algeria'),
(4, 'Andorra', 'AD', '376', 'EUR', '🇦🇩', 'andorra'),
(5, 'Angola', 'AO', '244', 'AOA', '🇦🇴', 'angola'),
(6, 'Antigua and Barbuda', 'AG', '1268', 'XCD', '🇦🇬', 'antigua-and-barbuda'),
(7, 'Argentina', 'AR', '54', 'ARS', '🇦🇷', 'argentina'),
(8, 'Armenia', 'AM', '374', 'AMD', '🇦🇲', 'armenia'),
(9, 'Australia', 'AU', '61', 'AUD', '🇦🇺', 'australia'),
(10, 'Austria', 'AT', '43', 'EUR', '🇦🇹', 'austria'),
(11, 'Azerbaijan', 'AZ', '994', 'AZN', '🇦🇿', 'azerbaijan'),
(12, 'Bahamas', 'BS', '1242', 'BSD', '🇧🇸', 'bahamas'),
(13, 'Bahrain', 'BH', '973', 'BHD', '🇧🇭', 'bahrain'),
(14, 'Bangladesh', 'BD', '880', 'BDT', '🇧🇩', 'bangladesh'),
(15, 'Barbados', 'BB', '1246', 'BBD', '🇧🇧', 'barbados'),
(16, 'Belarus', 'BY', '375', 'BYN', '🇧🇾', 'belarus'),
(17, 'Belgium', 'BE', '32', 'EUR', '🇧🇪', 'belgium'),
(18, 'Belize', 'BZ', '501', 'BZD', '🇧🇿', 'belize'),
(19, 'Benin', 'BJ', '229', 'XOF', '🇧🇯', 'benin'),
(20, 'Bhutan', 'BT', '975', 'BTN', '🇧🇹', 'bhutan'),
(21, 'Bolivia', 'BO', '591', 'BOB', '🇧🇴', 'bolivia'),
(22, 'Bosnia and Herzegovina', 'BA', '387', 'BAM', '🇧🇦', 'bosnia-and-herzegovina'),
(23, 'Botswana', 'BW', '267', 'BWP', '🇧🇼', 'botswana'),
(24, 'Brazil', 'BR', '55', 'BRL', '🇧🇷', 'brazil'),
(25, 'Brunei Darussalam', 'BN', '673', 'BND', '🇧🇳', 'brunei-darussalam'),
(26, 'Bulgaria', 'BG', '359', 'BGN', '🇧🇬', 'bulgaria'),
(27, 'Burkina Faso', 'BF', '226', 'XOF', '🇧🇫', 'burkina-faso'),
(28, 'Burundi', 'BI', '257', 'BIF', '🇧🇮', 'burundi'),
(29, 'Cabo Verde', 'CV', '238', 'CVE', '🇨🇻', 'cabo-verde'),
(30, 'Cambodia', 'KH', '855', 'KHR', '🇰🇭', 'cambodia'),
(31, 'Cameroon', 'CM', '237', 'XAF', '🇨🇲', 'cameroon'),
(32, 'Canada', 'CA', '1', 'CAD', '🇨🇦', 'canada'),
(33, 'Central African Republic', 'CF', '236', 'XAF', '🇨🇫', 'central-african-republic'),
(34, 'Chad', 'TD', '235', 'XAF', '🇹🇩', 'chad'),
(35, 'Chile', 'CL', '56', 'CLP', '🇨🇱', 'chile'),
(36, 'China', 'CN', '86', 'CNY', '🇨🇳', 'china'),
(37, 'Colombia', 'CO', '57', 'COP', '🇨🇴', 'colombia'),
(38, 'Comoros', 'KM', '269', 'KMF', '🇰🇲', 'comoros'),
(39, 'Congo', 'CG', '242', 'XAF', '🇨🇬', 'congo'),
(40, 'Congo, Democratic Republic of the', 'CD', '243', 'CDF', '🇨🇩', 'congo-democratic-republic'),
(41, 'Costa Rica', 'CR', '506', 'CRC', '🇨🇷', 'costa-rica'),
(42, 'Croatia', 'HR', '385', 'HRK', '🇭🇷', 'croatia'),
(43, 'Cuba', 'CU', '53', 'CUP', '🇨🇺', 'cuba'),
(44, 'Cyprus', 'CY', '357', 'EUR', '🇨🇾', 'cyprus'),
(45, 'Czech Republic', 'CZ', '420', 'CZK', '🇨🇿', 'czech-republic'),
(46, 'Denmark', 'DK', '45', 'DKK', '🇩🇰', 'denmark'),
(47, 'Djibouti', 'DJ', '253', 'DJF', '🇩🇯', 'djibouti'),
(48, 'Dominica', 'DM', '1767', 'XCD', '🇩🇲', 'dominica'),
(49, 'Dominican Republic', 'DO', '1809', 'DOP', '🇩🇴', 'dominican-republic'),
(50, 'Ecuador', 'EC', '593', 'USD', '🇪🇨', 'ecuador'),
(51, 'Egypt', 'EG', '20', 'EGP', '🇪🇬', 'egypt'),
(52, 'El Salvador', 'SV', '503', 'USD', '🇸🇻', 'el-salvador'),
(53, 'Equatorial Guinea', 'GQ', '240', 'XAF', '🇬🇶', 'equatorial-guinea'),
(54, 'Eritrea', 'ER', '291', 'ERN', '🇪🇷', 'eritrea'),
(55, 'Estonia', 'EE', '372', 'EUR', '🇪🇪', 'estonia'),
(56, 'Eswatini', 'SZ', '268', 'SZL', '🇸🇿', 'eswatini'),
(57, 'Ethiopia', 'ET', '251', 'ETB', '🇪🇹', 'ethiopia'),
(58, 'Fiji', 'FJ', '679', 'FJD', '🇫🇯', 'fiji'),
(59, 'Finland', 'FI', '358', 'EUR', '🇫🇮', 'finland'),
(60, 'France', 'FR', '33', 'EUR', '🇫🇷', 'france'),
(61, 'Gabon', 'GA', '241', 'XAF', '🇬🇦', 'gabon'),
(62, 'Gambia', 'GM', '220', 'GMD', '🇬🇲', 'gambia'),
(63, 'Georgia', 'GE', '995', 'GEL', '🇬🇪', 'georgia'),
(64, 'Germany', 'DE', '49', 'EUR', '🇩🇪', 'germany'),
(65, 'Ghana', 'GH', '233', 'GHS', '🇬🇭', 'ghana'),
(66, 'Greece', 'GR', '30', 'EUR', '🇬🇷', 'greece'),
(67, 'Grenada', 'GD', '1473', 'XCD', '🇬🇩', 'grenada'),
(68, 'Guatemala', 'GT', '502', 'GTQ', '🇬🇹', 'guatemala'),
(69, 'Guinea', 'GN', '224', 'GNF', '🇬🇳', 'guinea'),
(70, 'Guinea-Bissau', 'GW', '245', 'XOF', '🇬🇼', 'guinea-bissau'),
(71, 'Guyana', 'GY', '592', 'GYD', '🇬🇾', 'guyana'),
(72, 'Haiti', 'HT', '509', 'HTG', '🇭🇹', 'haiti'),
(73, 'Honduras', 'HN', '504', 'HNL', '🇭🇳', 'honduras'),
(74, 'Hungary', 'HU', '36', 'HUF', '🇭🇺', 'hungary'),
(75, 'Iceland', 'IS', '354', 'ISK', '🇮🇸', 'iceland'),
(76, 'India', 'IN', '91', 'INR', '🇮🇳', 'india'),
(77, 'Indonesia', 'ID', '62', 'IDR', '🇮🇩', 'indonesia'),
(78, 'Iran', 'IR', '98', 'IRR', '🇮🇷', 'iran'),
(79, 'Iraq', 'IQ', '964', 'IQD', '🇮🇶', 'iraq'),
(80, 'Ireland', 'IE', '353', 'EUR', '🇮🇪', 'ireland'),
(81, 'Israel', 'IL', '972', 'ILS', '🇮🇱', 'israel'),
(82, 'Italy', 'IT', '39', 'EUR', '🇮🇹', 'italy'),
(83, 'Jamaica', 'JM', '1876', 'JMD', '🇯🇲', 'jamaica'),
(84, 'Japan', 'JP', '81', 'JPY', '🇯🇵', 'japan'),
(85, 'Jordan', 'JO', '962', 'JOD', '🇯🇴', 'jordan'),
(86, 'Kazakhstan', 'KZ', '7', 'KZT', '🇰🇿', 'kazakhstan'),
(87, 'Kenya', 'KE', '254', 'KES', '🇰🇪', 'kenya'),
(88, 'Kiribati', 'KI', '686', 'AUD', '🇰🇮', 'kiribati'),
(89, 'Korea, Democratic People\'s Republic of', 'KP', '850', 'KPW', '🇰🇵', 'korea-democratic-peoples-republic-of'),
(90, 'Korea, Republic of', 'KR', '82', 'KRW', '🇰🇷', 'korea-republic-of'),
(91, 'Kuwait', 'KW', '965', 'KWD', '🇰🇼', 'kuwait'),
(92, 'Kyrgyzstan', 'KG', '996', 'KGS', '🇰🇬', 'kyrgyzstan'),
(93, 'Lao People\'s Democratic Republic', 'LA', '856', 'LAK', '🇱🇦', 'lao-peoples-democratic-republic'),
(94, 'Latvia', 'LV', '371', 'EUR', '🇱🇻', 'latvia'),
(95, 'Lebanon', 'LB', '961', 'LBP', '🇱🇧', 'lebanon'),
(96, 'Lesotho', 'LS', '266', 'LSL', '🇱🇸', 'lesotho'),
(97, 'Liberia', 'LR', '231', 'LRD', '🇱🇷', 'liberia'),
(98, 'Libya', 'LY', '218', 'LYD', '🇱🇾', 'libya'),
(99, 'Liechtenstein', 'LI', '423', 'CHF', '🇱🇮', 'liechtenstein'),
(100, 'Lithuania', 'LT', '370', 'EUR', '🇱🇹', 'lithuania'),
(101, 'Luxembourg', 'LU', '352', 'EUR', '🇱🇺', 'luxembourg'),
(102, 'Madagascar', 'MG', '261', 'MGA', '🇲🇬', 'madagascar'),
(103, 'Malawi', 'MW', '265', 'MWK', '🇲🇼', 'malawi'),
(104, 'Malaysia', 'MY', '60', 'MYR', '🇲🇾', 'malaysia'),
(105, 'Maldives', 'MV', '960', 'MVR', '🇲🇻', 'maldives'),
(106, 'Mali', 'ML', '223', 'XOF', '🇲🇱', 'mali'),
(107, 'Malta', 'MT', '356', 'EUR', '🇲🇹', 'malta'),
(108, 'Marshall Islands', 'MH', '692', 'USD', '🇲🇭', 'marshall-islands'),
(109, 'Mauritania', 'MR', '222', 'MRU', '🇲🇷', 'mauritania'),
(110, 'Mauritius', 'MU', '230', 'MUR', '🇲🇺', 'mauritius'),
(111, 'Mexico', 'MX', '52', 'MXN', '🇲🇽', 'mexico'),
(112, 'Micronesia (Federated States of)', 'FM', '691', 'USD', '🇫🇲', 'micronesia-federated-states-of'),
(113, 'Moldova (Republic of)', 'MD', '373', 'MDL', '🇲🇩', 'moldova-republic-of'),
(114, 'Monaco', 'MC', '377', 'EUR', '🇲🇨', 'monaco'),
(115, 'Mongolia', 'MN', '976', 'MNT', '🇲🇳', 'mongolia'),
(116, 'Montenegro', 'ME', '382', 'EUR', '🇲🇪', 'montenegro'),
(117, 'Morocco', 'MA', '212', 'MAD', '🇲🇦', 'morocco'),
(118, 'Mozambique', 'MZ', '258', 'MZN', '🇲🇿', 'mozambique'),
(119, 'Myanmar', 'MM', '95', 'MMK', '🇲🇲', 'myanmar'),
(120, 'Namibia', 'NA', '264', 'NAD', '🇳🇦', 'namibia'),
(121, 'Nauru', 'NR', '674', 'AUD', '🇳🇷', 'nauru'),
(122, 'Nepal', 'NP', '977', 'NPR', '🇳🇵', 'nepal'),
(123, 'Netherlands', 'NL', '31', 'EUR', '🇳🇱', 'netherlands'),
(124, 'New Zealand', 'NZ', '64', 'NZD', '🇳🇿', 'new-zealand'),
(125, 'Nicaragua', 'NI', '505', 'NIO', '🇳🇮', 'nicaragua'),
(126, 'Niger', 'NE', '227', 'XOF', '🇳🇪', 'niger'),
(127, 'Nigeria', 'NG', '234', 'NGN', '🇳🇬', 'nigeria'),
(128, 'North Macedonia', 'MK', '389', 'MKD', '🇲🇰', 'north-macedonia'),
(129, 'Norway', 'NO', '47', 'NOK', '🇳🇴', 'norway'),
(130, 'Oman', 'OM', '968', 'OMR', '🇴🇲', 'oman'),
(131, 'Pakistan', 'PK', '92', 'PKR', '🇵🇰', 'pakistan'),
(132, 'Palau', 'PW', '680', 'USD', '🇵🇼', 'palau'),
(133, 'Palestine, State of', 'PS', '970', 'ILS', '🇵🇸', 'palestine-state-of'),
(134, 'Panama', 'PA', '507', 'PAB', '🇵🇦', 'panama'),
(135, 'Papua New Guinea', 'PG', '675', 'PGK', '🇵🇬', 'papua-new-guinea'),
(136, 'Paraguay', 'PY', '595', 'PYG', '🇵🇾', 'paraguay'),
(137, 'Peru', 'PE', '51', 'PEN', '🇵🇪', 'peru'),
(138, 'Philippines', 'PH', '63', 'PHP', '🇵🇭', 'philippines'),
(139, 'Poland', 'PL', '48', 'PLN', '🇵🇱', 'poland'),
(140, 'Portugal', 'PT', '351', 'EUR', '🇵🇹', 'portugal'),
(141, 'Qatar', 'QA', '974', 'QAR', '🇶🇦', 'qatar'),
(142, 'Romania', 'RO', '40', 'RON', '🇷🇴', 'romania'),
(143, 'Russian Federation', 'RU', '7', 'RUB', '🇷🇺', 'russian-federation'),
(144, 'Rwanda', 'RW', '250', 'RWF', '🇷🇼', 'rwanda'),
(145, 'Saint Kitts and Nevis', 'KN', '1869', 'XCD', '🇰🇳', 'saint-kitts-and-nevis'),
(146, 'Saint Lucia', 'LC', '1758', 'XCD', '🇱🇨', 'saint-lucia'),
(147, 'Saint Vincent and the Grenadines', 'VC', '1784', 'XCD', '🇻🇨', 'saint-vincent-and-the-grenadines'),
(148, 'Samoa', 'WS', '685', 'WST', '🇼🇸', 'samoa'),
(149, 'San Marino', 'SM', '378', 'EUR', '🇸🇲', 'san-marino'),
(150, 'Sao Tome and Principe', 'ST', '239', 'STN', '🇸🇹', 'sao-tome-and-principe'),
(151, 'Saudi Arabia', 'SA', '966', 'SAR', '🇸🇦', 'saudi-arabia'),
(152, 'Senegal', 'SN', '221', 'XOF', '🇸🇳', 'senegal'),
(153, 'Serbia', 'RS', '381', 'RSD', '🇷🇸', 'serbia'),
(154, 'Seychelles', 'SC', '248', 'SCR', '🇸🇨', 'seychelles'),
(155, 'Sierra Leone', 'SL', '232', 'SLL', '🇸🇱', 'sierra-leone'),
(156, 'Singapore', 'SG', '65', 'SGD', '🇸🇬', 'singapore'),
(157, 'Slovakia', 'SK', '421', 'EUR', '🇸🇰', 'slovakia'),
(158, 'Slovenia', 'SI', '386', 'EUR', '🇸🇮', 'slovenia'),
(159, 'Solomon Islands', 'SB', '677', 'SBD', '🇸🇧', 'solomon-islands'),
(160, 'Somalia', 'SO', '252', 'SOS', '🇸🇴', 'somalia'),
(161, 'South Africa', 'ZA', '27', 'ZAR', '🇿🇦', 'south-africa'),
(162, 'South Sudan', 'SS', '211', 'SSP', '🇸🇸', 'south-sudan'),
(163, 'Spain', 'ES', '34', 'EUR', '🇪🇸', 'spain'),
(164, 'Sri Lanka', 'LK', '94', 'LKR', '🇱🇰', 'sri-lanka'),
(165, 'Sudan', 'SD', '249', 'SDG', '🇸🇩', 'sudan'),
(166, 'Suriname', 'SR', '597', 'SRD', '🇸🇷', 'suriname'),
(167, 'Sweden', 'SE', '46', 'SEK', '🇸🇪', 'sweden'),
(168, 'Switzerland', 'CH', '41', 'CHF', '🇨🇭', 'switzerland'),
(169, 'Syrian Arab Republic', 'SY', '963', 'SYP', '🇸🇾', 'syrian-arab-republic'),
(170, 'Tajikistan', 'TJ', '992', 'TJS', '🇹🇯', 'tajikistan'),
(171, 'Tanzania, United Republic of', 'TZ', '255', 'TZS', '🇹🇿', 'tanzania-united-republic-of'),
(172, 'Thailand', 'TH', '66', 'THB', '🇹🇭', 'thailand'),
(173, 'Timor-Leste', 'TL', '670', 'USD', '🇹🇱', 'timor-leste'),
(174, 'Togo', 'TG', '228', 'XOF', '🇹🇬', 'togo'),
(175, 'Tonga', 'TO', '676', 'TOP', '🇹🇴', 'tonga'),
(176, 'Trinidad and Tobago', 'TT', '1868', 'TTD', '🇹🇹', 'trinidad-and-tobago'),
(177, 'Tunisia', 'TN', '216', 'TND', '🇹🇳', 'tunisia'),
(178, 'Turkey', 'TR', '90', 'TRY', '🇹🇷', 'turkey'),
(179, 'Turkmenistan', 'TM', '993', 'TMT', '🇹🇲', 'turkmenistan'),
(180, 'Tuvalu', 'TV', '688', 'AUD', '🇹🇻', 'tuvalu'),
(181, 'Uganda', 'UG', '256', 'UGX', '🇺🇬', 'uganda'),
(182, 'Ukraine', 'UA', '380', 'UAH', '🇺🇦', 'ukraine'),
(183, 'United Arab Emirates', 'AE', '971', 'AED', '🇦🇪', 'united-arab-emirates'),
(184, 'United Kingdom of Great Britain and Northern Ireland', 'GB', '44', 'GBP', '🇬🇧', 'united-kingdom-of-great-britain-and-northern-ireland'),
(185, 'United States of America', 'US', '1', 'USD', '🇺🇸', 'united-states-of-america'),
(186, 'Uruguay', 'UY', '598', 'UYU', '🇺🇾', 'uruguay'),
(187, 'Uzbekistan', 'UZ', '998', 'UZS', '🇺🇿', 'uzbekistan'),
(188, 'Vanuatu', 'VU', '678', 'VUV', '🇻🇺', 'vanuatu'),
(189, 'Venezuela (Bolivarian Republic of)', 'VE', '58', 'VES', '🇻🇪', 'venezuela-bolivarian-republic-of'),
(190, 'Viet Nam', 'VN', '84', 'VND', '🇻🇳', 'viet-nam'),
(191, 'Yemen', 'YE', '967', 'YER', '🇾🇪', 'yemen'),
(192, 'Zambia', 'ZM', '260', 'ZMW', '🇿🇲', 'zambia'),
(193, 'Zimbabwe', 'ZW', '263', 'ZWL', '🇿🇼', 'zimbabwe');
